import { Inter } from 'next/font/google';
import './globals.css';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import NavBar from './component/NavBar'; // NavBar 컴포넌트를 불러옵니다.
import Footer from './component/Footer'; 

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	let session = await getServerSession(authOptions);
	// console.log('안녕하세요!', session.user.name);

	return (
		<html lang='en'>
			<body className={inter.className}>
				<NavBar session={session} /> {/* NavBar 컴포넌트를 사용합니다. */}
				{children}
				<Footer />
			</body>
		</html>
	);
}
